### ISSUE TITLE
Mismatched data on the business status

### ISSUE THREAD

**Issue by KosovareS** [opendatakosovo/open-arbk#106]
The data that are shown on the homepage: 
<img width="1216" alt="screen shot 2017-08-02 at 2 38 24 pm" src="https://user-images.githubusercontent.com/16719237/28874077-935d93a8-7790-11e7-99e4-d8884b339aab.png">

are not matching with the pie chart about the businesses status:
 
<img width="618" alt="screen shot 2017-08-02 at 2 38 36 pm" src="https://user-images.githubusercontent.com/16719237/28874094-a5b25502-7790-11e7-90c0-4ed4aebd3ba3.png">
<img width="558" alt="screen shot 2017-08-02 at 2 38 45 pm" src="https://user-images.githubusercontent.com/16719237/28874093-a5a50f0a-7790-11e7-9fe1-87b420dbb1f8.png">

**Comment by diamanthaxhimusa** [comment]
@KosovareS this is because the chart is showing data from 2000-2016 without 2017

**Comment by KosovareS** [comment]
@diamanthaxhimusa but in the header is written "nga 172 728 biznese të themeluara" which means that are included all the businesses

**Comment by diamanthaxhimusa** [comment]
@KosovareS yes in header all are included, but not in charts.

**Comment by KosovareS** [comment]
@diamanthaxhimusa then include also in this chart's header the number of businesses 2000-2016
