### ISSUE TITLE
In English use the word "Gender" instead of "Sex"

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/open-arbk#109]

**Comment by KosovareS** [comment]
<img width="1191" alt="screen shot 2017-08-17 at 9 29 12 am" src="https://user-images.githubusercontent.com/16719237/29400695-96dbdf4a-832e-11e7-9e4c-53c3021b5621.png">

**Comment by KosovareS** [comment]
<img width="1167" alt="screen shot 2017-08-17 at 9 30 18 am" src="https://user-images.githubusercontent.com/16719237/29400751-bfa9d1de-832e-11e7-9bf3-7cd75f86cb72.png">
<img width="1140" alt="screen shot 2017-08-17 at 9 30 27 am" src="https://user-images.githubusercontent.com/16719237/29400752-bfc97264-832e-11e7-97d7-4d9edaf6526e.png">

**Comment by KosovareS** [comment]
<img width="934" alt="screen shot 2017-08-17 at 9 30 59 am" src="https://user-images.githubusercontent.com/16719237/29400776-d0c5827e-832e-11e7-8db1-add821197eb9.png">

**Comment by KosovareS** [comment]
Please, @diamanthaxhimusa take care to translate this in any case.
