### ISSUE TITLE
Social media meta tags multilingual

### ISSUE THREAD

**Issue by diamanthaxhimusa** [opendatakosovo/open-arbk#118]
Use english translation when the website is sharen when on english language.

**Comment by KosovareS** [comment]
@diamanthaxhimusa here is the translation :
"Here you can find data of all registered businesses in Kosovo from 2000 - 2017."

**Comment by georgeslabreche** [comment]
@KosovareS that's bad English. Use this instead: "Search for and inspect business registration data from 2000 to 2017."

**Comment by KosovareS** [comment]
@georgeslabreche thanks!
