### ISSUE TITLE
Showing activities in maps

### ISSUE THREAD

**Issue by arianithetemi** [opendatakosovo/open-arbk#16]

**Comment by KosovareSahatqija** [comment]
@diamanthaxhimusa why in the Map by default is an option selected. See the pic bellow: 
<img width="1235" alt="screen shot 2017-05-12 at 2 08 58 pm" src="https://cloud.githubusercontent.com/assets/16719237/25997520/bc893110-371c-11e7-8692-6907488ab193.png">

**Comment by diamanthaxhimusa** [comment]
@KosovareSahatqija It was suggested by @georgeslabreche, to avoit the blank page. So by default an activity is selected to show up the map.

**Comment by KosovareSahatqija** [comment]
@diamanthaxhimusa There is a bug in Map visualization. In two cases isn't showing the name of the place. Bellow, you can find the attached images to be more clearly:
<img width="316" alt="screen shot 2017-05-12 at 2 17 59 pm" src="https://cloud.githubusercontent.com/assets/16719237/25997828/4ef99746-371e-11e7-838c-dc464e443a3a.png">
<img width="333" alt="screen shot 2017-05-12 at 2 19 00 pm" src="https://cloud.githubusercontent.com/assets/16719237/25997829/4efa5064-371e-11e7-9f8c-da3850ba0990.png">
