### ISSUE TITLE
Suggesting tabs for visualizations

### ISSUE THREAD

**Issue by KosovareSahatqija** [opendatakosovo/open-arbk#17]
As a user when I enter the visualization page, I do not know which type of visualizations the page provides without scrolling all the page. 
So, I suggest separating these charts in tabs and user can see from the beginning what the page provides.

**Comment by diamanthaxhimusa** [comment]
@georgeslabreche what do you suggest?

**Comment by georgeslabreche** [comment]
@diamanthaxhimusa I think this should be a dropdown navbar menu item. When you select one of the items, it scrolls you down to the visualization.
