### ISSUE TITLE
Secure platform with login.

### ISSUE THREAD

**Issue by diamanthaxhimusa** [opendatakosovo/open-arbk#25]

**Comment by georgeslabreche** [comment]
@diamanthaxhimusa keep in mind that there is no point in securing the platform with a basic auth if the username and password are hard-coded in publicly available source code:
https://github.com/opendatakosovo/open-arbk/blob/051e92a8a67f711d501ace0040bbfeb1a1298e99/app/__init__.py#L54-L55
