### ISSUE TITLE
Implement filters for Harta.

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/open-arbk#33]

**Comment by diamanthaxhimusa** [comment]
@georgeslabreche since we are showing a map, i guess we don't need to do a municipality filter. What do you suggest? thanks.

**Comment by KosovareSahatqija** [comment]
There should be like the "Aktiviteti" field. To have the "te gjitha" option by default selected. 
<img width="530" alt="screen shot 2017-05-17 at 3 11 12 pm" src="https://cloud.githubusercontent.com/assets/16719237/26155380/335e939e-3b13-11e7-8258-61c5a20da117.png">
