### ISSUE TITLE
Recommendation page.

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/open-arbk#36]
A page that lists 3 or 5 recommendations for ARBK on 1) how to make business registration data more open and 2) why they should do it.

We should have Albert produce a simple illustration for each of these recommendations. Illustrations should fit into the overall current design of the page.

**Comment by georgeslabreche** [comment]
@dafinaolluri work on this next week with Blina.

**Comment by dafinaolluri** [comment]
@georgeslabreche Okay.

**Comment by diamanthaxhimusa** [comment]
@georgeslabreche This task is in progress because i'm waiting @dafinaolluri for the complete text, since we are doing few changes on recommendation page's text.

**Comment by diamanthaxhimusa** [comment]
@KosovareS this task should be in backlog again, @georgeslabreche and I wanted to add some more recommendations, so we wait for @dafinaolluri provide the text.

**Comment by dafinaolluri** [comment]
@georgeslabreche  @KosovareS @diamanthaxhimusa I am just waiting for the meeting with GAP institute to confirm whether we should add that paragraph for the law or not.
