### ISSUE TITLE
Include a link or button in the header to download all the data.

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/open-arbk#39]
**Acceptance Criteria:**

- [ ] Data will disaggregated by Data e Aplikimit.
- [ ] User have the option to downloadable as either zipped JSON file or zipped CSV file.

**Comment by diamanthaxhimusa** [comment]
@georgeslabreche we need to upload the full data first.

**Comment by georgeslabreche** [comment]
@KosovareSahatqija @diamanthaxhimusa need to have the option to download zipped CSV file as well, I will update the description.

**Comment by KosovareSahatqija** [comment]
@diamanthaxhimusa this needs to be done also for CSV format

**Comment by georgeslabreche** [comment]
@KosovareSahatqija @diamanthaxhimusa remember to disaggregate by Data e Aplikimit.

**Comment by diamanthaxhimusa** [comment]
@KosovareSahatqija i am re-estimating this task because the proccess of generating files is taking time.

**Comment by diamanthaxhimusa** [comment]
@georgeslabreche @KosovareSahatqija we discussed with Georges and we are adding two options when downloading businesses by years(application date and establishment date)

**Comment by diamanthaxhimusa** [comment]
@georgeslabreche the server stopped the process again, this time generating the json and csv zip files. I think 1gb of ram is not enough, especially when we get all the data.
