### ISSUE TITLE
Social Media meta tags are missing.

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/open-arbk#40]

**Comment by diamanthaxhimusa** [comment]
@georgeslabreche @KosovareSahatqija  since we protected the platform with authentication we cant review this task.

**Comment by georgeslabreche** [comment]
@KosovareS @diamanthaxhimusa  is this still an issue?

**Comment by diamanthaxhimusa** [comment]
@georgeslabreche we reviewed it on facebook and worked fine, but twitter doesn't allow sharing with server ip's. So it can be closed, what do you say @KosovareS ?

**Comment by georgeslabreche** [comment]
@KosovareS @diamanthaxhimusa when there are blockers. Please make sure to create the Issues/Tasks that need to be done in order to unblock you. In this case it's setting up the domain.

**Comment by dafinaolluri** [comment]
@diamanthaxhimusa What happened with this task?
