### ISSUE TITLE
Bug in activity codes.

### ISSUE THREAD

**Issue by diamanthaxhimusa** [opendatakosovo/open-arbk#43]
@georgeslabreche there are some activity codes that are not full (4 digits).
Check this document for more explanation:
[doc.txt](https://github.com/opendatakosovo/open-arbk/files/1010755/doc.txt)

**Comment by georgeslabreche** [comment]
@diamanthaxhimusa @dafinaolluri need better sample of problematic JSON. Please paste 1 or 2 JSON samples using JSON formatting instead of a partial screenshot.

**Comment by diamanthaxhimusa** [comment]
@georgeslabreche i reopened this issue because the script now is getting killed and doesnt fix all documents. It worked before with 1/4 of the data, but now with 1/2 of the data is being killed. This script needs to be optimized. Thanks

**Comment by diamanthaxhimusa** [comment]
@georgeslabreche is this task still considered as a bug? Should we change it to heavy process for servers on low gb of ram?

**Comment by diamanthaxhimusa** [comment]
@KosovareS i suppose this task should be an epic, since it is fixed but just need some more extra ram for anyone who runs the script and it stops, or to run it continuously till the script is done fixing documents. @georgeslabreche what do you suggest?

**Comment by georgeslabreche** [comment]
@diamanthaxhimusa @dafinaolluri @KosovareS is this issue still an issue?

**Comment by georgeslabreche** [comment]
Still waiting to be updated on this.

**Comment by georgeslabreche** [comment]
@diamanthaxhimusa @dafinaolluri @KosovareS still waiting on update for this.

**Comment by diamanthaxhimusa** [comment]
@georgeslabreche it is if we count the implementation part in server, as long as the server needs ram to handle it, its an issue. The code is correct, the sript works, just needs a strong machine. In my oppinion, I think we close this issue and write a note to read me file for this.

**Comment by dafinaolluri** [comment]
@diamanthaxhimusa @georgeslabreche What happened with this task?

**Comment by georgeslabreche** [comment]
@diamanthaxhimusa this was fixed in the importer so shouldn't be a problem with new data. Why is this still an issue?
