### ISSUE TITLE
Search by business name

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/open-arbk#46]
**Description**
Add the option to search also by business name not only with the name of the owner.

![screen shot 2017-05-17 at 1 34 17 pm](https://cloud.githubusercontent.com/assets/24916965/26152022/97a67596-3b05-11e7-9e76-9014ecef4c39.png)

**Comment by diamanthaxhimusa** [comment]
@KosovareSahatqija i have re-estimated this task because we added a new search field and changed the searching logic.

**Comment by KosovareSahatqija** [comment]
@diamanthaxhimusa when searching(filtering) by clicking in "Kerko" button is not good to reset the searching fields because the user wants to know what he/she has been searching (filtering) for.

**Comment by KosovareSahatqija** [comment]
@diamanthaxhimusa "KERKO" button is not working
