### ISSUE TITLE
As a user I want to have the option to download by the year of establishment of company. 

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/open-arbk#48]
**Description**

The download feature needs to be in two formats JSON and CSV.

**Comment by KosovareSahatqija** [comment]
@diamanthaxhimusa  The CSV download file for the year 2011, 2012, 2013, 2014, 2015, 2016, 2017 is not working, it displays the NOT FOUND error:
<img width="832" alt="screen shot 2017-05-30 at 10 42 08 am" src="https://cloud.githubusercontent.com/assets/16719237/26575260/bfdfe384-4524-11e7-8a74-dd20816f6eab.png">
