### ISSUE TITLE
"Bizneset sipas viteve" is not showing

### ISSUE THREAD

**Issue by KosovareSahatqija** [opendatakosovo/open-arbk#57]
The chart for "Bizneset sipas viteve" category is not showing.
<img width="1258" alt="screen shot 2017-05-30 at 10 09 02 am" src="https://cloud.githubusercontent.com/assets/16719237/26574037/28b6cf4e-4520-11e7-8fbf-997c52f65d20.png">

**Comment by diamanthaxhimusa** [comment]
@KosovareSahatqija this is happening because we have the problem importing all the data into server, so for now this issue can't be solved! Thanks
