### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by KosovareSahatqija** [opendatakosovo/open-arbk#61]
Here I will list the design responsiveness bugs: 

* [ ] The header in iPhone 5s is messy:
![img_3916](https://cloud.githubusercontent.com/assets/16719237/26586206/c9daf962-454e-11e7-9764-4c076371be3b.PNG)

* [x] The filtering fields in iPhone 5s: 
![img_3917](https://cloud.githubusercontent.com/assets/16719237/26586340/3032a61a-454f-11e7-97df-f181b2324151.PNG)
![img_3918](https://cloud.githubusercontent.com/assets/16719237/26586339/302dcdac-454f-11e7-8ee4-fd0cce7bedd3.PNG)

* [x] Please use Bootstrap grid for these fields:
![img_3922](https://cloud.githubusercontent.com/assets/16719237/26631328/c75f03ba-460a-11e7-8877-5747c04fe4fe.PNG)

* [x] "Sektori" dropdown list is not responsive:
![img_3923](https://cloud.githubusercontent.com/assets/16719237/26631530/b1a40de4-460b-11e7-810f-0433a37fad69.PNG)

* [x] Make them look better (maybe equal width and height):
<img width="510" alt="screen shot 2017-05-31 at 2 25 27 pm" src="https://cloud.githubusercontent.com/assets/16719237/26631840/561bea8a-460d-11e7-9ccb-2d76ef46b22a.png">

**Comment by diamanthaxhimusa** [comment]
@KosovareSahatqija i am re-estimating this task since a lot of bugs came after the first review. thanks
