### ISSUE TITLE
In the data download page, we need an information message describing 1) where the data comes from (ARBK website),  2) how it was retrieved, and 3) specifying the date range of when the data was collected

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/open-arbk#79]
For the data collection date range, query for the smallest and largest value of timestamp. Just use sort(timestamp: 1) and sort(timestamp: -1) with limit(1)

**Comment by diamanthaxhimusa** [comment]
@KosovareS we need to add some more explanation since we removed the note on visualizations page, and we don't visualize the data before 2003 and after 2016, but we can download the information for 2002 and 2017.
