### ISSUE TITLE
Mismatched municipalities

### ISSUE THREAD

**Issue by diamanthaxhimusa** [opendatakosovo/open-arbk#90]
It seems that ARBK updated information on businesses, now they show their municipality not city/place. We have the old data which they showed city/place and we tried to match each city/place with the municipality, but some of cities/places are not matched correctly since there are many cities/places that have the same name but belong to different municipality.

**Comment by diamanthaxhimusa** [comment]
@georgeslabreche what do you suggest, how do we aproach this?

**Comment by dafinaolluri** [comment]
@georgeslabreche Do we have to scrape them again? Or we can leave it like that?

**Comment by georgeslabreche** [comment]
@diamanthaxhimusa @dafinaolluri resolve this by just leaving a note about it on the maps page.
