### ISSUE TITLE
Make ARBK multilingual to support English Language

### ISSUE THREAD

**Issue by dafinaolluri** [opendatakosovo/open-arbk#92]

**Comment by georgeslabreche** [comment]
@dafinaolluri this needs to be estimated.

**Comment by dafinaolluri** [comment]
@georgeslabreche Is this a priority?

**Comment by georgeslabreche** [comment]
@dafinaolluri no but it doesn't mean it can't be estimated. This goes back to our conversation about backlogging. We need, as much as possible, a good sized backlog for every project with estimated tasks. Priority does not matter in this case.

**Comment by georgeslabreche** [comment]
@dafinaolluri by backlog I mean icebox.
