### ISSUE TITLE
Basic stats on landing page.

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/open-arbk#93]
Make the stats very visible at first glance of the landing page.

- Total number of businesses in our database.
- How many active, with date range of oldest and newest registered.
- How many non active, with date range of oldest and newest registered.

**Comment by diamanthaxhimusa** [comment]
@georgeslabreche this task is taking longer to be finished because me and @Alikurti are thinking a spot were tu put these stats.

**Comment by georgeslabreche** [comment]
@diamanthaxhimusa please report estimate and deliver issues to @dafinaolluri @KosovareS

**Comment by georgeslabreche** [comment]
@diamanthaxhimusa not accepted. Numbers need to be formatted properly (whitespace for thousands separators)
