### ISSUE TITLE
Report on missing data

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/open-arbk#97]
In the website, we need to emphasize the problem of missing data.

**Question:** Should this be a visualization dedicated on missing data in the visualization page or its own dedicated page?

Present stats on how many ACTIVE and NON ACTIVE businesses do not have data available on:
- Activities (e.g. http://arbk.rks-gov.net/page.aspx?id=1,38,108000116)
- Owners (e.g. http://arbk.rks-gov.net/page.aspx?id=1,38,119000072)
- Establishment Date - Data e konstituimit (e.g. http://arbk.rks-gov.net/page.aspx?id=1,38,119001494)
- Application Date - Data e Aplikimit
- What else?

**Comment by georgeslabreche** [comment]
@diamanthaxhimusa you did not understand this Issue. I want content on the website that provides a report/insight on the extent of the problem of missing data, with statistics and maybe visualizations.

@dafinaolluri please make sure this is estimated and worked on.

**Comment by dafinaolluri** [comment]
@georgeslabreche Can this be put in the recommendation page or maybe we can just do a visualization?

**Comment by georgeslabreche** [comment]
@dafinaolluri, let's make it a dedicated "infographic" type page.

**Comment by dafinaolluri** [comment]
@diamanthaxhimusa Did you decide with Albertn and @KosovareS how to represent this task?

**Comment by dafinaolluri** [comment]
@georgeslabreche @KosovareS  @diamanthaxhimusa After a meeting we had with @diamanthaxhimusa  we agreed that this task need to be Icebox. Georges wants to create a new tab which is impossible at this time since Diamant is going to vacation tomorrow. It will be first thing to do after @diamanthaxhimusa comes back.

**Comment by diamanthaxhimusa** [comment]
@dafinaolluri  we need translations for this information, and if you can edit the text as well, thank you.

**Comment by dafinaolluri** [comment]
@diamanthaxhimusa Can you please add the text?

**Comment by dafinaolluri** [comment]
4 Biznese nuk kanë status të paraqitur.
523 Biznese nuk kanë të paraqitur emrin e pronarit/es/eve prej të cilave 464 prej tyre janë ende aktive.
7643 Biznese nuk kanë të paraqitur aktivitetet e tyre prej të cilave 759 janë ende aktive.
2269 Biznese nuk kanë datë të konstituimit prej të cilave 543 janë ende aktive.
62022 Biznese nuk kane të paraqitur numrin fiskal prej të cilave 52022 janë ende aktive.
